import type { AuditorExportManifestEntry, Employee, Evidence, PolicyAcknowledgement } from "@/lib/contracts";
import type { DemoDataStore } from "@/server/repositories/demo-repository";

interface ZipSourceFile {
  name: string;
  content: string;
}

interface ZipEntry extends ZipSourceFile {
  data: Buffer;
  crc32: number;
  localHeaderOffset: number;
}

const CRC32_TABLE = createCrc32Table();

export function createAuditorExportManifest(evidence: Evidence[]): AuditorExportManifestEntry[] {
  return evidence.map((item) => ({
    evidenceId: item.id,
    controlIds: item.controlIds,
    title: item.title,
    provider: item.provider,
    collectedAt: item.collectedAt,
  }));
}

const README_FILE_DESCRIPTIONS = [
  ["README.txt", "Package disclaimer, generation timestamp, and file descriptions."],
  ["controls.json", "Evaluated demo compliance controls and current statuses."],
  ["evidence.json", "Deterministic mock evidence collected from demo connectors."],
  ["employees.csv", "Demo employee roster and offboarding issue summary."],
  ["policies.csv", "Demo policy catalogue and acknowledgement completion counts."],
  ["policy-acknowledgements.csv", "Demo employee policy acknowledgement records."],
  ["risks.csv", "Demo risk assessment register."],
  ["connector-sync-history.json", "Most recent deterministic mock connector sync results."],
] as const;

export function createAuditorExportZip(
  generatedAt: string,
  store: DemoDataStore,
  acknowledgements: PolicyAcknowledgement[],
): Buffer {
  const syncHistory = store.syncRunHistory;
  const files: ZipSourceFile[] = [
    {
      name: "README.txt",
      content: createReadme(generatedAt),
    },
    {
      name: "controls.json",
      content: JSON.stringify(store.controls, null, 2),
    },
    {
      name: "evidence.json",
      content: JSON.stringify(store.evidence, null, 2),
    },
    {
      name: "employees.csv",
      content: createEmployeesCsv(store.employees),
    },
    {
      name: "policies.csv",
      content: toCsv(
        ["id", "name", "version", "description", "requiresAcknowledgement", "acknowledgedCount", "totalEmployeeCount"],
        store.policies.map((policy) => [
          policy.id,
          policy.name,
          policy.version,
          policy.description,
          policy.requiresAcknowledgement,
          policy.acknowledgedCount,
          policy.totalEmployeeCount,
        ]),
      ),
    },
    {
      name: "policy-acknowledgements.csv",
      content: toCsv(
        ["policyId", "employeeId", "acknowledgedAt"],
        acknowledgements.map((acknowledgement) => [
          acknowledgement.policyId,
          acknowledgement.employeeId,
          acknowledgement.acknowledgedAt,
        ]),
      ),
    },
    {
      name: "risks.csv",
      content: toCsv(
        [
          "id",
          "title",
          "description",
          "category",
          "likelihood",
          "impact",
          "severity",
          "status",
          "owner",
          "mitigationPlan",
          "createdAt",
          "updatedAt",
        ],
        store.risks.map((risk) => [
          risk.id,
          risk.title,
          risk.description,
          risk.category,
          risk.likelihood,
          risk.impact,
          risk.severity,
          risk.status,
          risk.owner,
          risk.mitigationPlan,
          risk.createdAt,
          risk.updatedAt,
        ]),
      ),
    },
    {
      name: "connector-sync-history.json",
      content: JSON.stringify(syncHistory, null, 2),
    },
  ];

  return createZip(files);
}

function createReadme(generatedAt: string): string {
  const descriptions = README_FILE_DESCRIPTIONS.map(([name, description]) => `- ${name}: ${description}`).join("\n");

  return [
    "SOC 2 Demonstration Audit Package",
    "",
    "This export was generated by a demonstration MVP.",
    "The contents are not an official SOC 2 attestation, audit report, legal opinion, or compliance determination.",
    `Generated at: ${generatedAt}`,
    "",
    "Included files:",
    descriptions,
    "",
  ].join("\n");
}

function createEmployeesCsv(employees: Employee[]): string {
  return toCsv(
    ["id", "name", "email", "source", "status", "startDate", "terminationDate", "openOffboardingIssueCount", "offboardingIssues"],
    employees.map((employee) => [
      employee.id,
      employee.name,
      employee.email,
      employee.source,
      employee.status,
      employee.startDate,
      employee.terminationDate,
      employee.offboardingIssues.filter((issue) => issue.status === "open").length,
      JSON.stringify(employee.offboardingIssues),
    ]),
  );
}

function toCsv(headers: string[], rows: Array<Array<string | number | boolean | null>>): string {
  const lines = [headers, ...rows].map((row) => row.map(escapeCsvValue).join(","));

  return `${lines.join("\n")}\n`;
}

function escapeCsvValue(value: string | number | boolean | null): string {
  const text = value === null ? "" : String(value);

  if (!/[",\r\n]/.test(text)) {
    return text;
  }

  return `"${text.replaceAll('"', '""')}"`;
}

function createZip(files: ZipSourceFile[]): Buffer {
  const localFileParts: Buffer[] = [];
  let offset = 0;

  const entries: ZipEntry[] = files.map((file) => {
    const name = Buffer.from(file.name, "utf8");
    const data = Buffer.from(file.content, "utf8");
    const localHeader = createLocalFileHeader(name, data);
    const entry: ZipEntry = {
      ...file,
      data,
      crc32: crc32(data),
      localHeaderOffset: offset,
    };

    localFileParts.push(localHeader, name, data);
    offset += localHeader.length + name.length + data.length;

    return entry;
  });

  const centralDirectoryOffset = offset;
  const centralDirectoryParts = entries.map((entry) => createCentralDirectoryHeader(entry));
  const centralDirectorySize = centralDirectoryParts.reduce((size, part) => size + part.length, 0);
  const endOfCentralDirectory = createEndOfCentralDirectory(entries.length, centralDirectorySize, centralDirectoryOffset);

  return Buffer.concat([...localFileParts, ...centralDirectoryParts, endOfCentralDirectory]);
}

function createLocalFileHeader(name: Buffer, data: Buffer): Buffer {
  const header = Buffer.alloc(30);
  const checksum = crc32(data);

  header.writeUInt32LE(0x04034b50, 0);
  header.writeUInt16LE(20, 4);
  header.writeUInt16LE(0, 6);
  header.writeUInt16LE(0, 8);
  header.writeUInt16LE(0, 10);
  header.writeUInt16LE(0, 12);
  header.writeUInt32LE(checksum, 14);
  header.writeUInt32LE(data.length, 18);
  header.writeUInt32LE(data.length, 22);
  header.writeUInt16LE(name.length, 26);
  header.writeUInt16LE(0, 28);

  return header;
}

function createCentralDirectoryHeader(entry: ZipEntry): Buffer {
  const name = Buffer.from(entry.name, "utf8");
  const header = Buffer.alloc(46);

  header.writeUInt32LE(0x02014b50, 0);
  header.writeUInt16LE(20, 4);
  header.writeUInt16LE(20, 6);
  header.writeUInt16LE(0, 8);
  header.writeUInt16LE(0, 10);
  header.writeUInt16LE(0, 12);
  header.writeUInt16LE(0, 14);
  header.writeUInt32LE(entry.crc32, 16);
  header.writeUInt32LE(entry.data.length, 20);
  header.writeUInt32LE(entry.data.length, 24);
  header.writeUInt16LE(name.length, 28);
  header.writeUInt16LE(0, 30);
  header.writeUInt16LE(0, 32);
  header.writeUInt16LE(0, 34);
  header.writeUInt16LE(0, 36);
  header.writeUInt32LE(0, 38);
  header.writeUInt32LE(entry.localHeaderOffset, 42);

  return Buffer.concat([header, name]);
}

function createEndOfCentralDirectory(entryCount: number, centralDirectorySize: number, centralDirectoryOffset: number): Buffer {
  const header = Buffer.alloc(22);

  header.writeUInt32LE(0x06054b50, 0);
  header.writeUInt16LE(0, 4);
  header.writeUInt16LE(0, 6);
  header.writeUInt16LE(entryCount, 8);
  header.writeUInt16LE(entryCount, 10);
  header.writeUInt32LE(centralDirectorySize, 12);
  header.writeUInt32LE(centralDirectoryOffset, 16);
  header.writeUInt16LE(0, 20);

  return header;
}

function createCrc32Table(): Uint32Array {
  const table = new Uint32Array(256);

  for (let index = 0; index < table.length; index += 1) {
    let checksum = index;

    for (let bit = 0; bit < 8; bit += 1) {
      checksum = checksum & 1 ? 0xedb88320 ^ (checksum >>> 1) : checksum >>> 1;
    }

    table[index] = checksum >>> 0;
  }

  return table;
}

function crc32(data: Buffer): number {
  let checksum = 0xffffffff;

  for (const byte of data) {
    checksum = CRC32_TABLE[(checksum ^ byte) & 0xff] ^ (checksum >>> 8);
  }

  return (checksum ^ 0xffffffff) >>> 0;
}
